"""
Reporter Agent.

Responsibilities:
- Produce an executive summary (LLM-assisted when available, template-based otherwise)
- Generate a Markdown report with findings table, remediation steps, and audit log
- Export a JSON artefact of the complete RunResult
- Persist both files to ``runs/<run_id>/``
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List

from jinja2 import Template

from core.evidence import save_run, save_report
from core.models import Finding, RunResult, ScanStatus, Severity

AGENT_NAME = "ReporterAgent"

# ── Jinja2 Markdown template ──────────────────────────────────────────────────
_MD_TEMPLATE = """\
# Vibe Hacking Agent — Security Assessment Report

**Run ID:** `{{ result.run_id }}`
**Target:** `{{ result.target }}`
**Started:** {{ result.started_at.strftime('%Y-%m-%d %H:%M:%S UTC') }}
**Completed:** {{ result.completed_at.strftime('%Y-%m-%d %H:%M:%S UTC') if result.completed_at else 'N/A' }}
**Status:** {{ result.status.value }}
**Mode:** {{ 'Active + Passive' if result.scope.active_testing else 'Passive only' }}
**Intensity:** {{ result.scope.test_intensity }}

---

## Scope

**In-scope targets:**
{% for t in result.scope.targets %}- `{{ t }}`
{% endfor %}
{% if result.scope.excluded_targets %}**Excluded:**
{% for t in result.scope.excluded_targets %}- `{{ t }}`
{% endfor %}{% endif %}
{% if result.scope.allowed_hours %}**Allowed testing hours:** {{ result.scope.allowed_hours }}{% endif %}

**Authorization note:** {{ result.scope.authorization_note or 'Confirmed by user.' }}

---

## Executive Summary

{{ executive_summary }}

---

## Findings

{% if not result.findings %}
> No findings were identified during this assessment.
{% else %}
| # | Severity | Confidence | Asset | Title |
|---|----------|-----------|-------|-------|
{% for f in result.findings %}| {{ loop.index }} | **{{ f.severity.value }}** | {{ f.confidence.value }} | `{{ f.affected_asset }}` | {{ f.title }} |
{% endfor %}

{% for f in result.findings %}
### [{{ f.severity.value }}] {{ f.title }}

- **Affected asset:** `{{ f.affected_asset }}`
- **Severity:** {{ f.severity.value }}
- **Confidence:** {{ f.confidence.value }}
- **Tool:** {{ f.tool }}
- **Detected at:** {{ f.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC') }}

**Description:**
{{ f.description }}

**Evidence:**
```
{{ f.evidence }}
```

**Remediation:**
{{ f.remediation }}

---
{% endfor %}
{% endif %}

## Asset Inventory

**Hosts discovered:** {{ result.asset_inventory.hosts | join(', ') or 'None' }}

**Technologies identified:** {{ result.asset_inventory.technologies | join(', ') or 'None' }}

{% if result.asset_inventory.open_ports %}
**Open ports:**
{% for host, ports in result.asset_inventory.open_ports.items() %}- `{{ host }}`: {{ ports | join(', ') }}
{% endfor %}{% endif %}

---

## Appendix: Audit Log

| Timestamp | Agent | Action |
|-----------|-------|--------|
{% for entry in result.audit_log %}| {{ entry.timestamp.strftime('%Y-%m-%d %H:%M:%S') }} | {{ entry.agent }} | {{ entry.action }} |
{% endfor %}

{% if result.audit_log %}
### Detailed Audit Trail

{% for entry in result.audit_log %}
**{{ entry.timestamp.strftime('%H:%M:%S') }} — {{ entry.agent }}: {{ entry.action }}**
{% if entry.command %}
*Command:* `{{ entry.command }}`
{% endif %}
{% if entry.output %}
```
{{ entry.output[:300] }}{% if entry.output | length > 300 %}…{% endif %}
```
{% endif %}

{% endfor %}
{% endif %}

---
*Report generated by Vibe Hacking Agent.  This report is for the exclusive use of the authorized recipient.*
"""


def run(state: Dict[str, Any]) -> Dict[str, Any]:
    """LangGraph node: generate final report."""
    if state.get("current_stage") in ("blocked", "failed"):
        return state

    result: RunResult = state["run_result"]
    result.add_audit(AGENT_NAME, "Generating final report")

    # ── Executive summary ─────────────────────────────────────────────────────
    result.executive_summary = _build_executive_summary(result, state)

    # ── Render Markdown ───────────────────────────────────────────────────────
    result.completed_at = datetime.now(timezone.utc)
    result.status = ScanStatus.COMPLETED
    md = _render_markdown(result)

    # ── Persist ───────────────────────────────────────────────────────────────
    report_path = save_report(result.run_id, md)
    result.report_path = str(report_path)
    save_run(result)

    result.add_audit(
        AGENT_NAME,
        "Report saved",
        output=f"Report: {report_path}\nFindings: {len(result.findings)}",
    )
    save_run(result)  # save again with the final audit entry

    state["current_stage"] = "complete"
    state["report_markdown"] = md
    return state


def _render_markdown(result: RunResult) -> str:
    tpl = Template(_MD_TEMPLATE)
    return tpl.render(result=result, executive_summary=result.executive_summary)


def _build_executive_summary(result: RunResult, state: Dict[str, Any]) -> str:
    """Build executive summary using LLM if available, otherwise template."""
    llm = state.get("llm")
    if llm:
        try:
            summary = _llm_executive_summary(result, llm)
            if summary:
                return summary
        except Exception:
            pass  # Fall through to template

    return _template_executive_summary(result)


def _template_executive_summary(result: RunResult) -> str:
    counts = {s: sum(1 for f in result.findings if f.severity == s) for s in Severity}
    total = len(result.findings)

    if total == 0:
        risk_level = "low"
        summary_line = "No significant security issues were identified during this assessment."
    elif counts[Severity.CRITICAL] > 0 or counts[Severity.HIGH] > 3:
        risk_level = "critical"
        summary_line = (
            f"The assessment identified {counts[Severity.CRITICAL]} critical and "
            f"{counts[Severity.HIGH]} high-severity issues requiring immediate attention."
        )
    elif counts[Severity.HIGH] > 0:
        risk_level = "high"
        summary_line = (
            f"The assessment identified {counts[Severity.HIGH]} high-severity issues "
            f"that should be remediated promptly."
        )
    elif counts[Severity.MEDIUM] > 0:
        risk_level = "medium"
        summary_line = (
            f"The assessment identified {counts[Severity.MEDIUM]} medium-severity issues "
            f"that should be addressed as part of normal security maintenance."
        )
    else:
        risk_level = "low"
        summary_line = "Only low-severity or informational findings were identified."

    tech_str = (
        f"Technologies in use include: {', '.join(result.asset_inventory.technologies)}. "
        if result.asset_inventory.technologies
        else ""
    )

    return (
        f"An automated security assessment was conducted against **{result.target}** "
        f"using the Vibe Hacking Agent.  The overall risk level is assessed as **{risk_level.upper()}**. "
        f"{summary_line}  "
        f"{tech_str}"
        f"A total of **{total}** findings were identified: "
        f"{counts[Severity.CRITICAL]} Critical, "
        f"{counts[Severity.HIGH]} High, "
        f"{counts[Severity.MEDIUM]} Medium, "
        f"{counts[Severity.LOW]} Low, "
        f"{counts[Severity.INFO]} Informational.  "
        f"All findings include remediation guidance in the detailed findings section."
    )


def _llm_executive_summary(result: RunResult, llm: Any) -> str:
    findings_summary = "\n".join(
        f"- [{f.severity.value}] {f.title}" for f in result.findings[:20]
    )
    prompt = (
        f"You are a senior security engineer writing an executive summary for a security assessment report. "
        f"Target: {result.target}. "
        f"Findings ({len(result.findings)} total):\n{findings_summary}\n\n"
        f"Write a concise executive summary (3-5 sentences) suitable for non-technical leadership. "
        f"Include overall risk level, key issues, and business impact."
    )
    response = llm.invoke(prompt)
    if hasattr(response, "content"):
        return response.content.strip()
    if isinstance(response, str):
        return response.strip()
    return ""
